### ISSUE TITLE
Don't use mutable types as kwarg defaults

### ISSUE THREAD

**Issue by dgouldin** [seandst/cfn-pyplates#37]
It's dangerous to use an empty list as the default for `Resource` attributes:

https://github.com/seandst/cfn-pyplates/blob/master/cfn_pyplates/core.py#L332

Rather, use `None` and then set to an empty list inside the function.

**Comment by seandst** [comment]
Calling mutable kwargs dangerous paints with a rather broad brush, as the mechanism does have valid uses. The danger doesn't apply in this case since `attributes` is never mutated when it's falsey.

A passed-in value will always be used, so the default value will only ever be used in [this check](https://github.com/seandst/cfn-pyplates/blob/master/cfn_pyplates/core.py#L342). Setting the `attributes` default to `None` is good for a variety of reasons (chief among them is removing any temptation to mutate a kwarg default), but setting it to an empty list inside the function is redundant.

git blame points to... @zircote: Did you have a specific reason for defaulting `attributes` to an empty list? Defaulting to `None` seems like a sane improvement, but not if there *is* behavior taking advantage of mutable kwargs that I'm just not seeing.

**Comment by tehsmyers** [comment]
Coming up on a year later; I'm still fine with the mutable kwargs...
